apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: mamicheck/celery:{{IMAGE_TAG}}
        envFrom:
            - secretRef:
                name: pydream-secret
        command: ["celery", "-A", "config", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
        resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 100Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  minReadySeconds: 90
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: mamicheck/celery:{{IMAGE_TAG}}
        envFrom:
            - secretRef:
                name: pydream-secret
        command: ["celery", "-A", "config", "worker", "-l", "info"]
        resources:
            limits:
              cpu: 150m
              memory: 350Mi
            requests:
              cpu: 100m
              memory: 250Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  minReadySeconds: 90
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600            
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: celery-worker-service
# spec:
#   selector:
#     app: celery-worker
#   ports:
#     - protocol: TCP
#       port: 5555
#       targetPort: 5555