apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: mamicheck/backend:{{IMAGE_TAG}}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: pydream-secret
          volumeMounts:
            - name: django-storage
              mountPath: /app/static
          lifecycle:
            postStart:
              exec:
                command: ["python", "manage.py", "migrate"]
          resources:
            limits:
              cpu: 150m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: django-storage
          persistentVolumeClaim:
            claimName: django-pvc-python
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  minReadySeconds: 90
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600        
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: django-service
# spec:
#   selector:
#     app: django
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#       nodePort: 31080 # port-range: 30000-32767
#   type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: django-migrate-job
# spec:
#   ttlSecondsAfterFinished: 3600 # Job will be deleted 1 hour after it finishes
#   template:
#     spec:
#       containers:
#         - name: migrate
#           image: mamicheck/backend:20
#           command: ["python", "manage.py", "migrate"]
#           envFrom:
#             - secretRef:
#                 name: pydream-secret
#           volumeMounts:
#             - name: django-storage
#               mountPath: /app/static
#       volumes:
#         - name: django-storage
#           persistentVolumeClaim:
#             claimName: django-pvc-python
#       restartPolicy: Never
#   backoffLimit: 4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc-python
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv-python
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: /data/django-pv