version: '3'
services:
  django:
    build: ./app
    container_name: djangoapp
    restart: always
    expose:
      - 8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    volumes:
      - ./app:/app/
    env_file:
      - ./chat_bot_project/.env.example
  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
volumes:
  postgres_volume: