version: '3'
services:
  django:
    build: ./
    container_name: djangoapp
    restart: always
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./chat_bot_project/.env.example
  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
  
  node:
    build: ./
    container_name: nexttapp
    restart: always
    ports:
      - 3005:3000
    volumes:
      - ./:/app   
volumes:
  postgres_volume: