FROM python:3.11-alpine

RUN apk update && apk add bash

SHELL ["/bin/bash", "-c"]

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .