# Generated by Django 4.2.3 on 2023-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('US', 'User'), ('AD', 'Admin'), ('MN', 'Manager')], default='US', max_length=10),
        ),
    ]
