# Generated by Django 4.1.5 on 2023-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
