# Generated by Django 4.1.5 on 2023-09-08 16:24

from django.db import migrations
from django.core.management import call_command

from accounts.apps import AccountsConfig
from config.settings import BASE_DIR

fixture = BASE_DIR / "accounts/migrations/fixtures/solutionhistoryconfig.json"


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label=AccountsConfig.name)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_solutionhistoryconfig_solutionhistory"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
