# Generated by Django 4.1.5 on 2023-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
