# Generated by Django 4.1.5 on 2023-12-06 11:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("img", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Dignities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dignities", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SolutionFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("functionality", models.CharField(max_length=200, null=True)),
                ("integration", models.CharField(max_length=800, null=True)),
                ("multiple", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolutionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Steps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SolutionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("properties", models.CharField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.CharField(max_length=800, null=True)),
                ("is_message", models.BooleanField(default=False)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solutions.solutionfilter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="solutionfilter",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="solutions.solutiongroup",
            ),
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("business_model", models.CharField(max_length=200)),
                ("business_area", models.CharField(max_length=100)),
                ("business_niche", models.CharField(max_length=100)),
                ("objective", models.CharField(max_length=100)),
                ("solution_type", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=300)),
                ("platform", models.CharField(max_length=100)),
                ("messengers", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="save", max_length=800, null=True
                    ),
                ),
                ("integration_with_CRM", models.CharField(max_length=100)),
                ("integration_with_payment_systems", models.CharField(max_length=100)),
                ("tasks", models.CharField(max_length=100)),
                ("actions_to_complete_tasks", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("price", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subtitle", models.CharField(max_length=300)),
                ("full_description", models.CharField(max_length=300)),
                ("cards_title", models.CharField(max_length=200)),
                ("cards_description", models.CharField(max_length=200)),
                ("steps_title", models.CharField(max_length=200)),
                ("steps_description", models.CharField(max_length=200)),
                (
                    "turnkey_platform",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("link", models.CharField(blank=True, max_length=800, null=True)),
                (
                    "links_to_platform",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("advantages", models.ManyToManyField(to="solutions.advantages")),
                ("cards", models.ManyToManyField(to="solutions.cards")),
                ("dignities", models.ManyToManyField(to="solutions.dignities")),
                ("filter", models.ManyToManyField(to="solutions.solutiontag")),
                ("steps", models.ManyToManyField(to="solutions.steps")),
            ],
        ),
    ]
