# Generated by Django 4.1.5 on 2023-10-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("img", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Dignities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dignities", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Steps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="solution",
            name="dignity",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="steps_text",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="steps_title",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="advantages",
        ),
        migrations.AddField(
            model_name="solution",
            name="cards",
            field=models.ManyToManyField(to="solutions.cards"),
        ),
        migrations.AddField(
            model_name="solution",
            name="dignities",
            field=models.ManyToManyField(to="solutions.dignities"),
        ),
        migrations.AddField(
            model_name="solution",
            name="steps",
            field=models.ManyToManyField(to="solutions.steps"),
        ),
        migrations.AddField(
            model_name="solution",
            name="advantages",
            field=models.ManyToManyField(to="solutions.advantages"),
        ),
    ]
