# Generated by Django 4.1.5 on 2024-01-23 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solutionfilter_status_solutiongroup_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_special', models.CharField(blank=True, max_length=100, null=True)),
                ('tags_of_rates', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='platform_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='platform_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='actions_to_complete_tasks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='solutions.advantages'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='business_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='business_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='business_niche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='solutions.cards'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cards_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cards_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='dignities',
        ),
        migrations.AlterField(
            model_name='solution',
            name='filter',
            field=models.ManyToManyField(blank=True, null=True, to='solutions.solutiontag'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='full_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='integration_with_CRM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='integration_with_payment_systems',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='messengers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='objective',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, to='solutions.steps'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='steps_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='steps_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tasks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='dignities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
    ]
