# Generated by Django 4.1.5 on 2024-02-20 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0002_solutionfilter_status_solutiongroup_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_special", models.CharField(blank=True, max_length=100, null=True)),
                ("tags_of_rates", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="solution",
            name="actions_to_complete_tasks",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="business_area",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="business_model",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="business_niche",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="cards_description",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="cards_title",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="integration_with_CRM",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="integration_with_payment_systems",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="messengers",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="objective",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="solution_type",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="turnkey_platform",
        ),
        migrations.AddField(
            model_name="steps",
            name="media",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="solution",
            name="advantages",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="cards",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="dignities",
        ),
        migrations.AlterField(
            model_name="solution",
            name="filter",
            field=models.ManyToManyField(
                blank=True, null=True, to="solutions.solutiontag"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="full_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="short_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name="solution",
            name="steps",
        ),
        migrations.AlterField(
            model_name="solution",
            name="steps_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="steps_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="tasks",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="solution",
            name="advantages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="cards",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solution",
            name="dignities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="steps",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
