# Generated by Django 4.1.5 on 2023-09-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('functionality', models.CharField(max_length=200, null=True)),
                ('integration', models.CharField(max_length=800, null=True)),
                ('multiple', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=800, null=True)),
                ('is_message', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platformfilter')),
            ],
        ),
        migrations.AddField(
            model_name='platformfilter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platformgroup'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.CharField(max_length=800)),
                ('turnkey_solutions', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=800, null=True)),
                ('link', models.CharField(max_length=800, null=True)),
                ('filter', models.ManyToManyField(to='platforms.platformtag')),
            ],
        ),
    ]
