# Generated by Django 4.1.5 on 2023-07-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='platformfilter',
            name='functionality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='platformfilter',
            name='integration',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='platformfilter',
            name='multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformtag',
            name='is_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platform',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platformimage'),
        ),
        migrations.AddField(
            model_name='platformtag',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platformimage'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platformimage'),
        ),
        migrations.AlterField(
            model_name='platformfilter',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platformimage'),
        ),
    ]
