# Generated by Django 4.1.5 on 2023-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platform",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="platformfilter",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="platformgroup",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="platformtag",
            name="is_active",
        ),
        migrations.AddField(
            model_name="platform",
            name="status",
            field=models.CharField(default="save", max_length=800),
        ),
        migrations.AddField(
            model_name="platformfilter",
            name="status",
            field=models.CharField(default="save", max_length=800),
        ),
        migrations.AddField(
            model_name="platformgroup",
            name="status",
            field=models.CharField(default="save", max_length=800),
        ),
        migrations.AddField(
            model_name="platformtag",
            name="status",
            field=models.CharField(default="save", max_length=800),
        ),
        migrations.AlterField(
            model_name="platform",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="platformfilter",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="platformgroup",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="platformtag",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
