# Generated by Django 4.1.5 on 2023-09-19 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_remove_platform_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='links_to_solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='platform',
            name='filter',
            field=models.ManyToManyField(null=True, to='platforms.platformtag'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='full_description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(default='save', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='turnkey_solutions',
            field=models.IntegerField(null=True),
        ),
    ]
