# Generated by Django 4.1.5 on 2023-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0002_platformfilter_functionality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformgroup",
            name="image",
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="platformtag",
            name="image",
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="platformtag",
            name="is_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="platform",
            name="price",
            field=models.IntegerField(),
        ),
    ]
