# Generated by Django 4.1.5 on 2023-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_platformgroup_image_platformtag_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='link',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
